---
repos:
  # Check if the commit message has a valid sign-off.
  - repo: https://github.com/gklein/check_signoff
    rev: v1.0.5
    hooks:
      - id: check-signoff

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Verify syntax of yaml and json files.
      - id: check-json

      # Makes sure that files end in a new line.
      - id: end-of-file-fixer

      # Trims trailing whitespace.
      - id: trailing-whitespace

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.2.0
    hooks:
      - id: helm-docs

  # Run commitlint check on the commit message.
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
