{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ddclient.fullname" . }}
  labels:
    {{- include "ddclient.labels" . | nindent 4 }}
stringData:
  ddclient.conf: |
    {{- .Values.config | nindent 4 }}
{{- end }}
